# -*- coding: utf-8 -*-
# Fontes da Anatomia A (Foresight na Seguros Unimed: o plano). Ordem = numeracao.

def L(u, t=None):
    return '<a href="%s">%s</a>' % (u, t or u.replace("https://", "").replace("http://", "").split("/")[0])

NOTA = """<div class="card">
<p><strong>Nota de método.</strong> <span class="sel sel-v">Verificado</span> indica afirmação apoiada em documento publicado e identificado, lido na íntegra ou no trecho citado. Fontes públicas acessadas em 8 de setembro de 2026, salvo indicação; as fontes do bench de ofertas, formações e plataformas foram verificadas em 2 de setembro de 2026 no documento irmão sobre a oferta do escritório de futuros e são reaproveitadas aqui sem nova pesquisa de preço. <span class="sel sel-i">Inferência</span> indica raciocínio construído sobre fontes verificadas sem que nenhuma o afirme diretamente; todo o desenho da função e todo total de custo somado estão nesta categoria. <span class="sel sel-e">Especulativo</span> indica hipótese sem base direta, oferecida para discussão. <span class="sel sel-p">Proposta</span> marca o que é desenho deste documento, a validar com as áreas.</p>
<p><strong>Sobre as fontes internas.</strong> As atas do grupo de trabalho SUSEP Vida e Ramos Elementares são citadas por meio do documento interno que as consolidou (fonte 6), sempre por função e nunca por nome, no tom de diagnóstico e não de sentença. Nenhum número interno de salário foi usado; toda faixa salarial é de mercado.</p>
<p><strong>Sobre datas de norma.</strong> Prazos da agenda da ANS e do plano da Susep são os publicados pelos reguladores e podem mudar; confirmar na fonte antes de levar a comitê.</p>
</div>"""

SOURCES = [
 # A. Seguros Unimed
 ("su_rs2025", 'Seguros Unimed. <em>Relatório de Sustentabilidade 2025</em> (padrão GRI, 200 páginas): Mapa Estratégico 2025-2028 e seus oito temas, modelo de execução (semanal, mensal, trimestral), 1º ciclo de Planejamento Integrado Estratégico em agosto de 2025 e início da revisão 2026-2028 em outubro de 2025, comitês e comissões, receita de R$ 8,53 bilhões (GRI 201-1), carteira por segmento, números do Sistema Unimed, Lei Complementar 213/2025 e horizontes de risco. ' + L("https://midias.segurosunimed.com.br/content/UMD_Relatorio_Sustentabilidade_25_Final__.pdf", "midias.segurosunimed.com.br (PDF)")),
 ("su_c666", 'Seguros Unimed. <em>Relatório de Sustentabilidade, Circular SUSEP 666/22, edição 2025</em> (data-base 31 de dezembro de 2024, 39 páginas): nove riscos de sustentabilidade classificados por horizonte, critérios de curto, médio e longo prazo, governança de riscos (COSO ERM e ISO 31000), matriz de materialidade 2023-2024, 1.973 colaboradores, prêmio emitido de R$ 1,18 bilhão nas sociedades SUSEP e mais de 13 mil corretores. ' + L("https://midias.segurosunimed.com.br/content/Relatorio-de-Sustentabilidade_Seguros-Unimed_Circular-666-22.pdf", "midias.segurosunimed.com.br (PDF)")),
 ("su_result", 'Unimed do Brasil, portal institucional. <em>Diversificação de negócios impulsiona Seguros Unimed a R$ 8,5 bilhões de faturamento em 2025</em>, 13 de março de 2026: crescimento de 14,5%, lucro líquido de R$ 737,6 milhões, sinistralidade consolidada de 72,8%, ROAE de 26,7%, 7 milhões de segurados, 19 escritórios regionais, crescimento por linha. ' + L("https://www.unimed.coop.br/site/-/diversifica%C3%A7%C3%A3o-de-neg%C3%B3cios-impulsiona-seguros-unimed-a-r-8-5-bilh%C3%B5es-de-faturamento-em-2025", "unimed.coop.br")),
 ("su_sobre", 'Seguros Unimed, área de relações com acionistas. <em>Sobre a Seguros Unimed</em>, atualizado em 10 de julho de 2026: origem em 1989 pela incorporação do Montecooper, posições de mercado por ramo (8ª em seguro saúde pelo Valor 1000; 21ª em previdência, 14ª em vida, 7ª em odonto e 20ª em ramos elementares pela Susep), cerca de 6 milhões de segurados. ' + L("https://ra.segurosunimed.com.br/ACompanhia/SobreASegurosUnimed", "ra.segurosunimed.com.br")),
 ("su_2mi", 'Unimed do Brasil, portal institucional. <em>Seguros Unimed supera 2 milhões de vidas na carteira de saúde e odonto</em>, 1º de abril de 2025: 905.998 vidas em saúde e 1.191.479 em odontologia em fevereiro de 2025. ' + L("https://www.unimed.coop.br/site/-/seguros-unimed-supera-2-milh%C3%B5es-de-vidas-na-carteira-de-sa%C3%BAde-e-odonto", "unimed.coop.br")),
 ("gt_susep", 'Projeto Estratégia (documento interno). <em>Anatomia Profunda: GT Susep Vida e RE</em>, 1º de setembro de 2026, consolidação de 24 documentos do grupo de trabalho (março a agosto de 2026) e duas transcrições: ritos existentes e cadências, escalada de decisões, capacidade das esteiras, Inteligência de Mercado (painel V4 e radar), 338 cooperativas no canal Unimed, 36% dos corretores de São Paulo que cotam uma vez e não voltam. Pasta Pesquisas do projeto.'),
 ("anat1", 'Projeto Estratégia (documento irmão). <em>A Anatomia Profunda: Foresight Corporativo</em>, 25 de agosto de 2026, 63 fontes: a tese do calendário de decisão, o roteiro genérico de doze meses, a governança, os produtos do mercado e os cinco erros de montagem. Página publicada no repositório do projeto. ' + L("https://eglbra.github.io/estrategia-futuros/AnatomiaProfundaForesight.html", "eglbra.github.io")),
 ("oferta", 'Projeto Estratégia (documento irmão). <em>Anatomia Profunda: A Oferta do Escritório de Futuros</em>, versão 4 de 2 de setembro de 2026, 45 fontes: bench de onze casas com preços públicos, gabaritos oficiais de artefato, custos de formação e plataforma, salários de mercado. Pasta Pesquisas do projeto.'),
 ("ebf_acervo", 'Escola Brasileira de Futuros. Acervo público de relatórios, kits de ferramentas e artigos (578 itens catalogados, 514 arquivos baixados, 5 GB), cópia local coletada em 25 e 26 de agosto de 2026 na pasta EBF_Acervo do projeto, com índice em CSV; inclui Global Risks Report 2026 do Fórum Econômico Mundial, Global Insurance Outlook 2024 da EY, Future of Health 2024 da Deloitte, World Social Report 2023 da ONU sobre envelhecimento e Brasil 2035 do Ipea. ' + L("https://ebf.rec.br/", "ebf.rec.br")),
 # B. Sistema Unimed
 ("ampla", 'Revista Ampla. <em>O futuro e o Sistema Unimed: como buscar a perenidade?</em>, 28 de outubro de 2024: fala do presidente da Unimed do Brasil ("o que nos trouxe até aqui não é o que vai nos levar adiante"), envelhecimento, custos, novos concorrentes, hub de inovação com mais de 300 Unimeds e núcleo de avaliação de tecnologias em saúde. ' + L("https://revistaampla.com.br/o-futuro-e-o-sistema-unimed-como-buscar-perenidade/", "revistaampla.com.br")),
 ("facunimed", 'Faculdade Unimed. <em>Assessoria para implantação de Planejamento Estratégico</em> em cooperativas do sistema, participativa e alinhada à ANS e às acreditadoras. ' + L("https://www.faculdadeunimed.edu.br/solucoes-corporativas/planejamento-estrategico/", "faculdadeunimed.edu.br")),
 ("exame_unimed", 'Exame. <em>"O cooperativismo coloca as pessoas no centro das decisões", diz presidente da Unimed do Brasil</em>: 340 cooperativas e mais de 20,9 milhões de beneficiários em planos médicos e odontológicos. ' + L("https://exame.com/negocios/cooperativismo-pessoas-centro-decisoes-unimed/", "exame.com")),
 # C. Regulacao e futuro datado
 ("susep_plano", 'Susep. <em>Susep aprova Plano de Regulação para 2026</em>, 22 de dezembro de 2025 (Resolução Susep nº 72, de 17 de dezembro de 2025): temas de prioridade 1 e 2, entre eles a regulamentação da Lei 15.040/2024 e da Lei Complementar 213/2025, seguro catástrofe, seguro de vida universal, sandbox, open insurance, regras prudenciais, de governança e de conduta, sustentabilidade e divulgação financeira em padrão internacional. ' + L("https://www.gov.br/susep/pt-br/central-de-conteudos/noticias/2025/dezembro/susep-aprova-plano-de-regulacao-para-2026", "gov.br/susep")),
 ("ans_agenda", 'ANS. <em>Agenda Regulatória 2026-2028: temas regulatórios</em> (quadro oficial com prazos por trimestre): reajuste coletivo (4º trimestre de 2026), novo Sistema de Informações de Beneficiários (4º trimestre de 2026), portabilidade (4º trimestre de 2026), modelos assistenciais coordenados com base na Atenção Primária (2º trimestre de 2027), remuneração baseada em valor (4º trimestre de 2027), padrão TISS e dados assistenciais (4º trimestre de 2027), doenças preexistentes (2º trimestre de 2028), revisão do IDSS (4º trimestre de 2028) e estudos preliminares sobre pacto intergeracional, judicialização e cartões de desconto. ' + L("https://www.gov.br/ans/pt-br/acesso-a-informacao/participacao-da-sociedade/agenda-regulatoria/Agenda_Regulatria_20262028_B.pdf", "gov.br/ans (PDF)")),
 ("lei15040", 'Brasil. <em>Lei nº 15.040, de 9 de dezembro de 2024</em>, que dispõe sobre normas de seguro privado (marco legal dos contratos de seguro), em vigor desde dezembro de 2025. ' + L("https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/l15040.htm", "planalto.gov.br")),
 ("lc213", 'Brasil. <em>Lei Complementar nº 213, de 15 de janeiro de 2025</em>, que dispõe sobre cooperativas de seguros e grupos de proteção patrimonial mutualista; e Susep, nota de 17 de janeiro de 2025 sobre a publicação. ' + L("https://www.planalto.gov.br/ccivil_03/leis/lcp/Lcp213.htm", "planalto.gov.br") + ' , ' + L("https://www.gov.br/susep/pt-br/central-de-conteudos/noticias/2025/janeiro/publicada-lei-que-trata-das-cooperativas-de-seguros-e-dos-grupos-de-protecao-patrimonial-mutualistas", "gov.br/susep")),
 ("orsa", 'Susep. <em>Publicada a Resolução CNSP que dispõe sobre o ORSA e a gestão de capital</em> (Resolução CNSP nº 471, de 25 de setembro de 2024): autoavaliação prospectiva de riscos e solvência ao longo do horizonte de planejamento de três anos, sob estresse, obrigatória para os segmentos S1 e S2, com prazos em 31 de dezembro de 2025 e, para testes de estresse reversos do S1, 31 de dezembro de 2026. ' + L("https://www.gov.br/susep/pt-br/central-de-conteudos/noticias/2024/outubro/publicada-a-resolucao-cnsp-que-dispoe-sobre-o-orsa-e-a-gestao-de-capital", "gov.br/susep")),
 ("seg388", 'CNSP. <em>Resolução CNSP nº 388, de 8 de setembro de 2020</em>: segmentação das supervisionadas (S1 a S4) por provisões técnicas e prêmios; S2 exige provisões de ao menos 0,2% e prêmios de ao menos 0,9% do total do mercado. ' + L("https://www.legisweb.com.br/legislacao/?id=401177", "legisweb.com.br")),
 ("ans_cbr", 'ANS. <em>Capital regulatório</em>: capital baseado em riscos das operadoras (Resolução Normativa nº 569/2022) e fatores reduzidos para quem cumpre as práticas mínimas de governança da RN 518/2022. ' + L("https://www.gov.br/ans/pt-br/assuntos/operadoras/regulacao-prudencial-acompanhamento-assistencial-e-economico-financeiro/regulacao-prudencial-1/capital-regulatorio", "gov.br/ans")),
 ("ibge", 'IBGE, Agência de Notícias. <em>População do país vai parar de crescer em 2041</em>, 22 de agosto de 2024 (Projeções da População, revisão 2024): pico de 220,4 milhões em 2041, 199,2 milhões em 2070, 37,8% de pessoas com 60 anos ou mais em 2070, idade média de 48,4 anos em 2070. ' + L("https://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/41056-populacao-do-pais-vai-parar-de-crescer-em-2041", "agenciadenoticias.ibge.gov.br")),
 ("iess", 'IESS. <em>VCMH/IESS</em>, índice de variação do custo médico-hospitalar, edição de julho de 2026 (publicada em agosto de 2026): 14,5% em doze meses, com terapias em 30,7%, consultas em 12,8% e internações em 12,6%. ' + L("https://www.iess.org.br/vcmhiess", "iess.org.br")),
 ("cnseg_pdms", 'CNseg. <em>Plano de Desenvolvimento do Mercado de Seguros (PDMS) vai impulsionar setor a atingir a marca de 10% do PIB em 2030</em>, plano lançado em 16 de março de 2023 com cerca de 65 iniciativas. ' + L("https://cnseg.org.br/noticias/plano-de-desenvolvimento-do-mercado-de-seguros-pdms-vai-impulsionar-setor-a-atingir-a-marca-de-10-do-pib-em-2030.html", "cnseg.org.br")),
 # D. Radar pronto (gratuito)
 ("axa", 'AXA e Ipsos. <em>Future Risks Report 2025</em>, 12ª edição, outubro de 2025: 3.600 especialistas de 57 países e 23 mil cidadãos de 18 países; mudança climática em primeiro pelo quinto ano, instabilidade geopolítica em segundo, segurança cibernética em terceiro, inteligência artificial e dados em quarto, mudança demográfica entra no top 10. Relatório gratuito. ' + L("https://www.axa.com/en/news/future-risks-report-2025", "axa.com") + ' , ' + L("https://www.ipsos.com/sites/default/files/ct/news/documents/2025-10/axa-future-risks-report-2025-rapport-complet.pdf", "ipsos.com (PDF)")),
 ("sonar", 'Swiss Re Institute. <em>SONAR</em>, série anual desde 2013 de riscos emergentes captados por plataforma interna de colaboração de subscritores, gestores de clientes e especialistas; edição 2025 com oito riscos emergentes, calor extremo à frente. ' + L("https://www.swissre.com/institute/research/sonar.html", "swissre.com") + ' , ' + L("https://www.swissre.com/institute/research/sonar/sonar2025.html", "SONAR 2025")),
 ("ec_sfr", 'Comissão Europeia. <em>2025 Strategic Foresight Report: Resilience 2.0</em> (COM(2025) 484). ' + L("https://commission.europa.eu/document/download/bdba60f0-abb3-42f8-b5be-fd35d693b289_en?filename=SFR2025-Report_web.pdf", "commission.europa.eu (PDF)")),
 ("uk_toolkit", 'Government Office for Science (Reino Unido). <em>The Futures Toolkit</em>, edição 2024: doze ferramentas, varredura de uma página, matriz importância por certeza, cenários em cinco passos e teste de estratégia com veredito em semáforo. ' + L("https://assets.publishing.service.gov.uk/media/66c4493f057d859c0e8fa778/futures-toolkit-edition-2.pdf", "gov.uk (PDF)")),
 ("oecd_toolkit", 'OCDE. <em>Strategic Foresight Toolkit for Resilient Public Policy</em>, 2025: cinco módulos e 25 disrupções com campos fixos. ' + L("https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/01/foresight-toolkit-for-resilient-public-policy_9ad1cd60/bcdd9304-en.pdf", "oecd.org (PDF)")),
 ("csf", 'Centre for Strategic Futures (Singapura). <em>Foresight 2024</em> e <em>Driving Forces 2040</em> (17 forças e 5 cartas curinga). ' + L("https://file.go.gov.sg/csfforesight2024.pdf", "go.gov.sg (PDF)")),
 ("undp", 'PNUD. <em>Foresight Playbook</em>, 2022, com apêndice de ferramentas: varredura que parte de como a liderança decide e campos do sinal. ' + L("https://www.undp.org/sites/g/files/zskgke326/files/2022-08/UNDP-RBAP-Foresight-Playbook-2022.pdf", "undp.org (PDF)")),
 ("sicredi", 'Sicredi Pioneira. <em>Foresight: Relatório de Cenários Futuros</em> (69 páginas): 45 oficinas com cerca de 980 pessoas (associados, colaboradores, parceiros, poder público, fornecedores), 4.200 linhas condensadas em 125, 12 desejos, 16 medos, 27 tendências, 32 sinais fracos, 48 cisnes negros e seis cenários para 2030 e 2050. ' + L("https://sicredipioneira.com.br/files/estrategia-pioneira-foresight-relatorio.pdf", "sicredipioneira.com.br (PDF)")),
 # E. Redes e formacao
 ("millennium", 'The Millennium Project. <em>Brazil Node</em>: nó brasileiro formado em 2000, composto pelo Núcleo de Estudos do Futuro da PUC-SP (vinte anos em 2024) e pelo Laboratório do Futuro da Coppe/UFRJ; tradução do relatório Trabalho/Tecnologia 2050. ' + L("https://www.millennium-project.org/overview/nodes/brazil-node/", "millennium-project.org") + ' , ' + L("https://www.pucsp.br/~nef/projetos/projeto_millenium.htm", "pucsp.br/~nef") + ' , ' + L("https://labfuturo.cos.ufrj.br/", "labfuturo.cos.ufrj.br")),
 ("cgee", 'Centro de Gestão e Estudos Estratégicos (CGEE), organização social vinculada ao Ministério da Ciência, Tecnologia e Inovação, dedicada a estudos prospectivos. ' + L("https://www.cgee.org.br/", "cgee.org.br")),
 ("apf", 'Association of Professional Futurists e World Futures Studies Federation, associações internacionais do campo. ' + L("https://www.apf.org/", "apf.org") + ' , ' + L("https://wfsf.org/", "wfsf.org")),
 ("hyper", 'Hyper Island Brasil. <em>Curso Explorando Futuros</em>, R$ 2.990 (acesso em 2 de setembro de 2026). ' + L("https://www.hyperisland.com.br/products/curso-explorando-futuros", "hyperisland.com.br")),
 ("espm", 'ESPM. <em>Master em Planejamento e Foresight Estratégico</em> (EAD, 360 horas), R$ 21.103 à vista (acesso em 2 de setembro de 2026). ' + L("https://www.espm.br/cursos/pos-graduacao/mba-master/master-em-planejamento-e-foresight-estrategico-ead/", "espm.br")),
 ("fdc", 'Fundação Dom Cabral. <em>Foresight e tecnologia na sala do conselho</em>, 32 horas, R$ 16.000 (acesso em 2 de setembro de 2026). ' + L("https://www.fdc.org.br/curta-media-duracao/foresight-tech-ia-na-sala-do-conselho", "fdc.org.br")),
 ("houston", 'University of Houston. <em>Professional Certificate in Foresight</em>, US$ 2.000 na versão virtual (acesso em 2 de setembro de 2026). ' + L("https://www.houstonforesight.org/level-up-your-strategic-foresight-skills-this-fall-virtual-live/", "houstonforesight.org")),
 ("iftf", 'Institute for the Future. <em>Foresight Essentials Training</em>, US$ 6.500 (US$ 4.500 para governo e sem fins lucrativos), 25 ferramentas (acesso em 2 de setembro de 2026). ' + L("https://www.iftf.org/foresightessentials/for-individuals/foresight-essentials-training/", "iftf.org")),
 ("cifs", 'Copenhagen Institute for Futures Studies. Cursos de €1.350 a €2.600, palestras de €5 a 10 mil e treinamento organizacional desde €8.000 (acesso em 2 de setembro de 2026). ' + L("https://www.cifs.dk/services/courses", "cifs.dk/courses") + ' , ' + L("https://www.cifs.dk/services/organisational-training", "cifs.dk/training")),
 ("fibres", 'FIBRES. Preços públicos da plataforma de radar: Business €6.900 por ano (10 usuários) e Enterprise €19.800 por ano (100 usuários) (acesso em 2 de setembro de 2026). ' + L("https://www.fibresonline.com/pricing", "fibresonline.com")),
 ("shaping", 'Shaping Tomorrow (desde US$ 19.800 por 10 licenças) e TrendWatching (Enterprise desde US$ 490 por mês) (acesso em 2 de setembro de 2026). ' + L("https://www.shapingtomorrow.com/webtext/447", "shapingtomorrow.com") + ' , ' + L("https://info.trendwatching.com/members-faq", "trendwatching.com")),
 ("wfut", 'W Futurismo. Consultoria com estudos de horizonte superior a dez anos, observatórios internos e futurista em residência; certificação em sua 24ª turma (acesso em 2 de setembro de 2026). ' + L("https://wfuturismo.com/consultoria/", "wfuturismo.com")),
 ("casas_br", 'Casas brasileiras de futuros e tendências: Box1824, Echos, MJV e Inova Consulting (acesso em 2 de setembro de 2026). ' + L("https://box1824.com/", "box1824.com") + ' , ' + L("https://echos.cc/school/", "echos.cc") + ' , ' + L("https://services.mjvinnovation.com/pt-br/futuresdesign/", "mjvinnovation.com") + ' , ' + L("https://www.inovaconsulting.com.br/", "inovaconsulting.com.br")),
 ("kairos", 'Kairos Future. Catálogo de consultoria (análise de cenários, radar de tendências, túnel de vento) e academia (Certified Future Strategist, €7.000) (acesso em 2 de setembro de 2026). ' + L("https://www.kairosfuture.com/consulting/", "kairosfuture.com")),
 ("ftsg", 'Future Today Strategy Group. Serviços nomeados e o Convergence Outlook gratuito, que substituiu o relatório anual de tendências (acesso em 2 de setembro de 2026). ' + L("https://ftsg.com/convergence/", "ftsg.com")),
 ("salarios", 'Salários de mercado para analista de inteligência de mercado: CAGED via Salario.com.br (julho de 2025 a junho de 2026: média R$ 4.886, mediana R$ 3.946 entre 76.070 contratos CLT) e régua Robert Half 2026 (pleno R$ 6.600 a 11.800; sênior R$ 8.250 a 14.800) (acesso em 2 de setembro de 2026). ' + L("https://www.salario.com.br/profissao/analista-de-inteligencia-de-mercado-cbo-142335/", "salario.com.br") + ' , ' + L("https://www.roberthalf.com/br/pt/vagas-detalhes/analista-de-inteligencia-de-mercado-g", "roberthalf.com")),
 # F. Evidencia do campo
 ("rohrbeck", 'Rohrbeck, R.; Kum, M. E. <em>Corporate foresight and its impact on firm performance: a longitudinal analysis</em>. Technological Forecasting and Social Change, v. 129, 2018: 83 empresas avaliadas em 2008 e medidas até 2015; as vigilantes com 16% de lucratividade contra 12% da média e crescimento de valor de mercado 200% acima da média. ' + L("https://www.sciencedirect.com/science/article/pii/S0040162517302287", "sciencedirect.com")),
 ("bain", 'Bain &amp; Company. <em>Management Tools &amp; Trends 2023</em>: o uso de planejamento de cenários e contingência caiu do pico de 70% para 19%, com satisfação de 30% muito satisfeitos e 6% insatisfeitos. ' + L("https://www.bain.com/insights/management-tools-and-trends-2023/", "bain.com")),
 ("scoblic", 'Scoblic, J. P. <em>Learning from the Future</em>. Harvard Business Review, julho e agosto de 2020: cenários como ensaio de decisão. ' + L("https://hbr.org/2020/07/learning-from-the-future", "hbr.org")),
 ("klein", 'Klein, G. <em>Performing a Project Premortem</em>. Harvard Business Review, setembro de 2007: a técnica do exame prévio de fracasso, apoiada na pesquisa de Mitchell, Russo e Pennington (1989) sobre retrospectiva prospectiva, que eleva em 30% a identificação correta de causas. ' + L("https://hbr.org/2007/09/performing-a-project-premortem", "hbr.org")),
]

GRUPOS = [
 ("A Seguros Unimed e os documentos do projeto", ["su_rs2025","su_c666","su_result","su_sobre","su_2mi","gt_susep","anat1","oferta","ebf_acervo"]),
 ("O Sistema Unimed", ["ampla","facunimed","exame_unimed"]),
 ("Regulação e demografia: o futuro que já tem data", ["susep_plano","ans_agenda","lei15040","lc213","orsa","seg388","ans_cbr","ibge","iess","cnseg_pdms"]),
 ("O radar pronto, gratuito", ["axa","sonar","ec_sfr","uk_toolkit","oecd_toolkit","csf","undp","sicredi"]),
 ("Redes, formação, plataformas e casas", ["millennium","cgee","apf","hyper","espm","fdc","houston","iftf","cifs","fibres","shaping","wfut","casas_br","kairos","ftsg","salarios"]),
 ("Evidência do campo", ["rohrbeck","bain","scoblic","klein"]),
]
